create database if not exists nationsDb;
use nationsDb;
  create table if not exists nations(
    nation_name varchar(20) not null,
    primary key (nation_name),
    area_id int not null,
    ideology_id int not null,
    team_id int not null,
    sea tinyint not null,
    nf tinyint not null
  )engine=Innodb;

insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("メキシコ",2,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("グアテマラ",2,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("エルサルバドル",2,2,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ホンジュラス",2,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ニカラグア",2,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("コスタリカ",2,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("パナマ",2,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("キューバ",2,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ハイチ",2,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ドミニカ共和国",2,2,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("チリ",3,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("アルゼンチン",3,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ウルグアイ",3,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("パラグアイ",3,3,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ボリビア",3,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ペルー",3,2,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("エクアドル",3,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("コロンビア",3,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ベネズエラ",3,2,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ブラジル",3,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("カナダ自治領",1,1,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("アメリカ合衆国",1,1,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("リベリア",4,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("エチオピア",4,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("南アフリカ",4,1,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("アイルランド",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イギリス",5,1,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ポルトガル",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("スペイン",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("フランス",5,1,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イタリア",5,2,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("スイス",5,1,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ベルギー",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("オランダ",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ドイツ",5,2,2,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("デンマーク",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("オーストリア",5,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ハンガリー王国",5,4,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ユーゴスラビア",5,4,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("アルバニア",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ギリシャ",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ブルガリア",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ルーマニア王国",5,4,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("チェコスロバキア",5,1,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ポーランド",5,4,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("リトアニア",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ラトビア",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("エストニア",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ノルウェー",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("スウェーデン",5,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("フィンランド",5,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ソビエト連邦(west)",5,3,3,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イラク",7,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("サウジアラビア",7,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("オマーン",7,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イエメン",7,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イラン",6,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("アフガニスタン",6,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イギリス領インド",6,4,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ネパール",6,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ブータン",6,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("チベット",6,4,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("タンヌ・トゥヴァ",6,3,3,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("モンゴル",6,3,3,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("西北三馬",6,4,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("中華民国",6,4,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("雲南",6,4,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("広西軍閥",6,4,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("中国共産党",6,3,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("山西",6,4,4,2,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ソビエト連邦(east)",6,3,3,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("蒙古国",6,2,4,2,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("満州国",6,2,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("大日本帝国",6,2,4,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("シャム",8,4,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("イギリス領マラヤ",8,1,1,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("オランダ領東インド",8,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("フィリピン",8,1,4,1,2);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("オーストラリア",8,1,1,1,1);
insert into nations(nation_name,area_id,ideology_id,team_id,sea,nf) values("ニュージーランド",8,1,1,1,1);
